[0m13:24:56.924971 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017458F1E6D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017458EF6FD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017458DBE590>]}


============================== 13:24:56.978504 | d6e9c23d-ad15-4d62-adfc-4c5ba1dc804b ==============================
[0m13:24:56.978504 [info ] [MainThread]: Running with dbt=1.5.0
[0m13:24:56.981474 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\felix\\.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m13:24:56.984590 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\dev\fvgm-spec\learn_dbt\chinook_duckdb\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:24:56.988666 [debug] [MainThread]: Command `dbt seed` failed at 13:24:56.987650 after 0.17 seconds
[0m13:24:56.989646 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017458F2EC10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017458F00050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017452AF7050>]}
[0m13:24:56.991746 [debug] [MainThread]: Flushing usage events
[0m13:30:58.011426 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021C1A23DD10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021C1A24C910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021C1A24CED0>]}


============================== 13:30:58.015658 | 89c22410-999b-4a15-ad56-cc931c845121 ==============================
[0m13:30:58.015658 [info ] [MainThread]: Running with dbt=1.5.0
[0m13:30:58.016088 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'D:\\dev\\fvgm-spec\\learn_dbt\\chinook_duckdb', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'D:\\dev\\fvgm-spec\\learn_dbt\\chinook_duckdb\\logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m13:30:58.899147 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '89c22410-999b-4a15-ad56-cc931c845121', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021C1A476A10>]}
[0m13:30:58.910464 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '89c22410-999b-4a15-ad56-cc931c845121', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021C1A487B50>]}
[0m13:30:58.920561 [debug] [MainThread]: checksum: 4568eb639a77b8fcb3a1f4a07856f42b1ff63f1376652889143968e1dbdafbda, vars: {}, profile: , target: , version: 1.5.0
[0m13:30:58.922460 [info ] [MainThread]: Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m13:30:58.923514 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '89c22410-999b-4a15-ad56-cc931c845121', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021C1A46A1D0>]}
[0m13:30:58.934227 [error] [MainThread]: Encountered an error:
'utf-8' codec can't decode byte 0xfa in position 713: invalid start byte
[0m13:30:58.968371 [error] [MainThread]: Traceback (most recent call last):
  File "D:\Users\felix\anaconda3\envs\dbt\Lib\site-packages\dbt\cli\requires.py", line 86, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\felix\anaconda3\envs\dbt\Lib\site-packages\dbt\cli\requires.py", line 71, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\felix\anaconda3\envs\dbt\Lib\site-packages\dbt\cli\requires.py", line 142, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\felix\anaconda3\envs\dbt\Lib\site-packages\dbt\cli\requires.py", line 168, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\felix\anaconda3\envs\dbt\Lib\site-packages\dbt\cli\requires.py", line 215, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\felix\anaconda3\envs\dbt\Lib\site-packages\dbt\cli\requires.py", line 242, in wrapper
    manifest = ManifestLoader.get_full_manifest(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\felix\anaconda3\envs\dbt\Lib\site-packages\dbt\parser\manifest.py", line 227, in get_full_manifest
    manifest = loader.load()
               ^^^^^^^^^^^^^
  File "D:\Users\felix\anaconda3\envs\dbt\Lib\site-packages\dbt\parser\manifest.py", line 273, in load
    file_reader.read_files()
  File "D:\Users\felix\anaconda3\envs\dbt\Lib\site-packages\dbt\parser\read_files.py", line 193, in read_files
    self.read_files_for_project(project, file_types)
  File "D:\Users\felix\anaconda3\envs\dbt\Lib\site-packages\dbt\parser\read_files.py", line 200, in read_files_for_project
    project_files[file_type_info["parser"]] = read_files_for_parser(
                                              ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\felix\anaconda3\envs\dbt\Lib\site-packages\dbt\parser\read_files.py", line 157, in read_files_for_parser
    source_files = get_source_files(
                   ^^^^^^^^^^^^^^^^^
  File "D:\Users\felix\anaconda3\envs\dbt\Lib\site-packages\dbt\parser\read_files.py", line 138, in get_source_files
    fb_list.append(load_seed_source_file(fp, project.project_name))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\felix\anaconda3\envs\dbt\Lib\site-packages\dbt\parser\read_files.py", line 120, in load_seed_source_file
    file_contents = load_file_contents(match.absolute_path, strip=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\felix\anaconda3\envs\dbt\Lib\site-packages\dbt\clients\system.py", line 98, in load_file_contents
    to_return = handle.read().decode("utf-8")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfa in position 713: invalid start byte

[0m13:30:58.970875 [debug] [MainThread]: Command `dbt seed` failed at 13:30:58.970875 after 0.99 seconds
[0m13:30:58.971391 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021C1A24D5D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021C13D87050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021C13D87090>]}
[0m13:30:58.971391 [debug] [MainThread]: Flushing usage events
